import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.14.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendPasswordResetEmail, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/12.14.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, serverTimestamp, enableIndexedDbPersistence } from 'https://www.gstatic.com/firebasejs/12.14.0/firebase-firestore.js';

const today = new Date().toISOString().slice(0,10);
const APP_CACHE = 'vektreise_cloud_cache_v1';
const quotes = ['Små valg, hver dag, blir store resultater over tid.','Du trenger ikke være perfekt – bare jevn.','Målet er ikke å være streng. Målet er å være stabil.','Vinn uka. Da følger resultatene etter.','Neste gode valg er alltid nærmere enn du tror.','Bygg et system du faktisk liker å bruke.'];
const habits = [{id:'water', text:'Drukket nok vann'},{id:'greens', text:'Spist grønt i dag'},{id:'activity', text:'Vært i aktivitet'},{id:'noSnack', text:'Holdt kontroll på småspising'}];
const byId = id => document.getElementById(id);
const setText = (id, value) => { const el = byId(id); if (el) el.textContent = value; };
const val = id => String((byId(id)?.value ?? '')).trim();
const num = (id, fallback=0) => { const n = parseFloat(val(id)); return Number.isFinite(n) ? n : fallback; };
const fmt = (n, digits=1) => Number(n || 0).toLocaleString('no-NO', { minimumFractionDigits: digits, maximumFractionDigits: digits });
const fmtInt = n => Number(Math.round(Number(n || 0))).toLocaleString('no-NO');
const clamp = (n,min,max) => Math.max(min, Math.min(max, n));
const pct = (value,total) => total > 0 ? clamp((value/total)*100, 0, 100) : 0;
const sameDay = (a,b) => String(a || '').slice(0,10) === String(b || '').slice(0,10);
const parseDateSafe = s => { const d = new Date(s); return isNaN(d) ? null : d; };
const cryptoRandom = () => crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const daysAgo = days => { const d = new Date(); d.setHours(0,0,0,0); d.setDate(d.getDate() - days); return d; };
const safe = (str='') => String(str).replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let app = null, auth = null, db = null, firebaseReady = false, currentUser = null, saveTimer = null, authMode = 'login';
function defaultState(){ return { profile:{ displayName:'', heightCm:197, age:'', sex:'', activityLevel:'1.55', manualCalorieTarget:'', startWeight:120, currentWeight:120, goalWeight:110, why:''}, goals:{activitiesPerWeek:4, minutesPerWeek:180, stepsPerDay:8000}, weights:[{id:cryptoRandom(), date:today, weight:120}], meals:[], activities:[], checkins:{} }; }
function cacheKey(uid='demo'){ return `${APP_CACHE}_${uid}`; }
function mergeDeep(base, extra){ const out = structuredClone ? structuredClone(base) : JSON.parse(JSON.stringify(base)); for(const k in extra || {}){ if(extra[k] && typeof extra[k] === 'object' && !Array.isArray(extra[k]) && out[k] && typeof out[k] === 'object' && !Array.isArray(out[k])) out[k] = mergeDeep(out[k], extra[k]); else out[k] = extra[k]; } return out; }
function loadLocalCache(uid='demo'){ try{ const raw = localStorage.getItem(cacheKey(uid)); if(!raw) return defaultState(); return mergeDeep(defaultState(), JSON.parse(raw)); } catch { return defaultState(); } }
let state = loadLocalCache();
function saveLocalCache(uid='demo'){ localStorage.setItem(cacheKey(uid), JSON.stringify(state)); }
function setNotice(text, kind='info'){ const el = byId('saveIndicator'); el.textContent = text; const styles = {info:['rgba(56,189,248,.14)','rgba(56,189,248,.35)','#e0f2fe'],success:['rgba(34,197,94,.14)','rgba(74,222,128,.35)','#dcfce7'],warn:['rgba(250,204,21,.14)','rgba(250,204,21,.35)','#fff7cc'],danger:['rgba(248,113,113,.14)','rgba(248,113,113,.35)','#fee2e2']}[kind] || ['rgba(56,189,248,.14)','rgba(56,189,248,.35)','#e0f2fe']; el.style.background = styles[0]; el.style.borderColor = styles[1]; el.style.color = styles[2]; }
function updateFirebaseStatus(){ const pill = byId('firebaseStatusPill'); if(firebaseReady) pill.textContent = currentUser ? 'Firebase tilkoblet • Synker per bruker' : 'Firebase klar • Venter på innlogging'; else pill.textContent = 'Demo-modus • Legg inn Firebase-konfig'; }
function showAuthMessage(msg=''){ setText('authMessage', msg); }
function setAuthMode(mode){ authMode = mode; document.querySelectorAll('[data-tab]').forEach(el => el.classList.toggle('active', el.dataset.tab === mode)); byId('authNameWrap').classList.toggle('hidden', mode !== 'signup'); byId('authPassword').parentElement.classList.toggle('hidden', mode === 'reset'); setText('authActionBtn', mode === 'login' ? 'Logg inn' : mode === 'signup' ? 'Opprett bruker' : 'Send e-post for nullstilling'); showAuthMessage(''); }
async function initFirebase(){ const cfg = window.__FIREBASE_CONFIG__; const setupNotice = byId('authSetupNotice'); if(!cfg || !cfg.apiKey || cfg.apiKey.includes('LIM_INN')){ firebaseReady = false; setupNotice.classList.remove('hidden'); setupNotice.textContent = 'Firebase er ikke konfigurert enda. Fyll ut firebase-config.js for å aktivere ekte flerbruker.'; byId('authOverlay').classList.add('hidden'); setText('userLabel', 'Demo-modus (lokal)'); updateFirebaseStatus(); renderAll(); setNotice('Kjører i demo-modus. Legg inn Firebase-konfig for ekte flerbruker.', 'warn'); return; } try{ app = initializeApp(cfg); auth = getAuth(app); db = getFirestore(app); try{ await enableIndexedDbPersistence(db); } catch {} firebaseReady = true; setupNotice.classList.add('hidden'); updateFirebaseStatus(); onAuthStateChanged(auth, async user => { currentUser = user || null; updateFirebaseStatus(); if(currentUser){ byId('authOverlay').classList.add('hidden'); setText('userLabel', currentUser.displayName || currentUser.email || 'Innlogget'); state = loadLocalCache(currentUser.uid); await pullFromCloud(); renderAll(); setNotice('Innlogget og klar. Endringer lagres automatisk til Firestore.', 'success'); } else { setText('userLabel', 'Ikke logget inn'); byId('authOverlay').classList.remove('hidden'); renderAll(); } }); } catch(err){ firebaseReady = false; setupNotice.classList.remove('hidden'); setupNotice.textContent = `Firebase kunne ikke initialiseres: ${err.message}`; byId('authOverlay').classList.remove('hidden'); updateFirebaseStatus(); } }
async function cloudDocRef(){ if(!db || !currentUser) return null; return doc(db, 'users', currentUser.uid, 'app', 'main'); }
async function pullFromCloud(){ if(!firebaseReady || !currentUser) return; try{ const ref = await cloudDocRef(); const snap = await getDoc(ref); if(snap.exists()){ const remote = snap.data()?.state || {}; state = mergeDeep(defaultState(), remote); saveLocalCache(currentUser.uid); setNotice('Data lastet fra skyen.', 'success'); } else await pushToCloud(true); } catch(err){ setNotice(`Kunne ikke laste skydata: ${err.message}`, 'warn'); } }
async function pushToCloud(initial=false){ if(!firebaseReady || !currentUser) return; try{ const ref = await cloudDocRef(); await setDoc(ref, { uid: currentUser.uid, email: currentUser.email || '', updatedAt: serverTimestamp(), appVersion: 'cloud-v1', state }, { merge: true }); saveLocalCache(currentUser.uid); setNotice(initial ? 'Førstegangslagring fullført.' : 'Endringer synkronisert til Firestore.', 'success'); } catch(err){ setNotice(`Synk feilet: ${err.message}`, 'danger'); } }
function scheduleSave(){ saveLocalCache(currentUser?.uid || 'demo'); if(!firebaseReady || !currentUser){ setNotice('Lokal lagring oppdatert. Slå på Firebase for sky-synk.', 'warn'); return; } setNotice('Endringer registrert – synker om et øyeblikk…', 'info'); clearTimeout(saveTimer); saveTimer = setTimeout(() => pushToCloud(false), 900); }
function bmi(weight, heightCm){ const h = Number(heightCm || 0) / 100; return h > 0 ? Number(weight || 0)/(h*h) : 0; }
function estimateCalories(){ const manual = parseFloat(state.profile.manualCalorieTarget); if(Number.isFinite(manual) && manual > 0) return {target: manual, message: `Bruker manuelt kalorimål: ${fmtInt(manual)} kcal/dag.`}; const age = parseFloat(state.profile.age), sex = state.profile.sex, weight = parseFloat(state.profile.currentWeight), height = parseFloat(state.profile.heightCm), level = parseFloat(state.profile.activityLevel || '1.55'); if(!(Number.isFinite(age) && age > 0 && sex && Number.isFinite(weight) && Number.isFinite(height))) return {target:null, message:'Legg inn alder og kjønn for å beregne moderat kalorimål, eller sett manuelt mål.'}; const bmr = 10*weight + 6.25*height - 5*age + (sex === 'male' ? 5 : -161); const maintenance = bmr * level; const target = Math.max(maintenance - 500, 1500); return {target, maintenance, message:`Estimert vedlikehold: ${fmtInt(maintenance)} kcal. Foreslått mål: ${fmtInt(target)} kcal/dag.`}; }
function syncUi(){ const p = state.profile; byId('displayName').value = p.displayName || ''; byId('heightCm').value = p.heightCm ?? ''; byId('age').value = p.age ?? ''; byId('sex').value = p.sex || ''; byId('activityLevel').value = p.activityLevel || '1.55'; byId('manualCalorieTarget').value = p.manualCalorieTarget || ''; byId('startWeight').value = p.startWeight ?? ''; byId('currentWeight').value = p.currentWeight ?? ''; byId('goalWeight').value = p.goalWeight ?? ''; byId('whyText').value = p.why || ''; byId('goalActivitiesPerWeek').value = state.goals.activitiesPerWeek; byId('goalMinutesPerWeek').value = state.goals.minutesPerWeek; byId('goalStepsPerDay').value = state.goals.stepsPerDay; const c = state.checkins[today] || { habits:{}, waterGlasses:'', mood:'' }; byId('waterGlasses').value = c.waterGlasses || ''; byId('dailyMood').value = c.mood || ''; ['weighDate','mealDate','activityDate'].forEach(id => byId(id).value ||= today); habits.forEach(h => updateHabitUi(h.id, !!c.habits?.[h.id])); }
function renderSummary(){ const p = state.profile; setText('startWeightView', `${fmt(p.startWeight)} kg`); setText('currentWeightView', `${fmt(p.currentWeight)} kg`); setText('goalWeightView', `${fmt(p.goalWeight)} kg`); setText('bmiView', fmt(bmi(p.currentWeight, p.heightCm), 1)); const totalToLose = Math.max(0, Number(p.startWeight || 0) - Number(p.goalWeight || 0)); const lost = Math.max(0, Number(p.startWeight || 0) - Number(p.currentWeight || 0)); const progress = pct(lost, totalToLose); setText('progressText', `${fmt(lost)} kg av ${fmt(totalToLose)} kg`); setText('goalPercentText', `${fmt(progress,0)} %`); byId('goalBar').style.width = `${progress}%`; byId('planNotice').textContent = estimateCalories().message; }
function sevenDayStats(){ const from = daysAgo(6); const meals = state.meals.filter(x => parseDateSafe(x.date) >= from); const acts = state.activities.filter(x => parseDateSafe(x.date) >= from); return { meals: meals.length, acts: acts.length, minutes: acts.reduce((s,x)=>s+(parseFloat(x.duration)||0),0), steps: acts.reduce((s,x)=>s+(parseFloat(x.steps)||0),0) }; }
function dayHasEntries(date){ return state.meals.some(x => sameDay(x.date,date)) || state.activities.some(x => sameDay(x.date,date)) || state.weights.some(x => sameDay(x.date,date)) || !!state.checkins[date]; }
function calculateStreak(){ let streak = 0; const d = new Date(); d.setHours(0,0,0,0); while(true){ const key = d.toISOString().slice(0,10); if(dayHasEntries(key)) streak++; else break; d.setDate(d.getDate()-1); if(streak > 1000) break; } return streak; }
function renderGoals(){ const week = sevenDayStats(); const avgSteps = week.steps / 7; setText('weeklyMealsView', String(week.meals)); setText('weeklyActsView', String(week.acts)); setText('weeklyMinutesView', fmtInt(week.minutes)); setText('weeklyStepsView', fmtInt(week.steps)); setText('weeklyActsText', `${week.acts}/${state.goals.activitiesPerWeek}`); setText('weeklyMinsText', `${fmtInt(week.minutes)}/${fmtInt(state.goals.minutesPerWeek)}`); setText('weeklyStepsText', `${fmtInt(avgSteps)}/${fmtInt(state.goals.stepsPerDay)}`); byId('weeklyActsBar').style.width = `${pct(week.acts, state.goals.activitiesPerWeek)}%`; byId('weeklyMinsBar').style.width = `${pct(week.minutes, state.goals.minutesPerWeek)}%`; byId('weeklyStepsBar').style.width = `${pct(avgSteps, state.goals.stepsPerDay)}%`; setText('streakView', String(calculateStreak())); }
function renderScore(){ const todayMeals = state.meals.filter(x => sameDay(x.date,today)); const todayActs = state.activities.filter(x => sameDay(x.date,today)); const checkin = state.checkins[today] || { habits:{} }; const todayCalories = todayMeals.reduce((s,m)=>s+(parseFloat(m.calories)||0),0); const target = estimateCalories().target; const minutes = todayActs.reduce((s,a)=>s+(parseFloat(a.duration)||0),0); const steps = todayActs.reduce((s,a)=>s+(parseFloat(a.steps)||0),0); const activeHabits = habits.filter(h => checkin.habits?.[h.id]).length; const breakdown = []; let score = 0; if(todayMeals.length >= 3){ score += 2; breakdown.push(['+2','Minst tre måltider logget i dag.']); } else if(todayMeals.length > 0){ score += 1; breakdown.push(['+1','Du har startet matloggen i dag.']); } else breakdown.push(['0','Ingen matlogg registrert enda i dag.']); if(minutes >= 30 || steps >= state.goals.stepsPerDay){ score += 2; breakdown.push(['+2','Sterk aktivitet i dag.']); } else if(minutes > 0 || steps > 0){ score += 1; breakdown.push(['+1','Noe aktivitet er registrert.']); } else breakdown.push(['0','Ingen aktivitet logget enda i dag.']); if(activeHabits >= 3){ score += 2; breakdown.push(['+2',`Vaner huket av: ${activeHabits}/${habits.length}.`]); } else if(activeHabits >= 1){ score += 1; breakdown.push(['+1',`Vaner huket av: ${activeHabits}/${habits.length}.`]); } else breakdown.push(['0','Ingen vaner huket av enda.']); if((checkin.waterGlasses || 0) >= 8){ score += 1; breakdown.push(['+1','Godt med vann i dag.']); } else breakdown.push(['0','Registrer minst 8 vannglass for ekstra poeng.']); if(target && todayCalories > 0){ if(todayCalories <= target){ score += 3; breakdown.push(['+3',`Kalorier i dag (${fmtInt(todayCalories)}) er innenfor målet.`]); } else if(todayCalories <= target * 1.1){ score += 1; breakdown.push(['+1','Du er litt over, men fortsatt nær planen.']); } else breakdown.push(['0','Kaloriinntaket er et stykke over målet i dag.']); } else breakdown.push(['0','Kaloripoeng beregnes når du logger mat med kcal eller setter mål.']); score = clamp(score,0,10); setText('scoreValue', String(score)); byId('scoreRing').style.background = `conic-gradient(var(--accent) ${score*36}deg, rgba(255,255,255,.08) ${score*36}deg)`; setText('scorePill', score >= 8 ? 'Knallbra dag' : score >= 5 ? 'Solid på vei' : score >= 2 ? 'God start' : 'Klar for neste steg'); byId('scoreList').innerHTML = breakdown.map(([a,b]) => `<li><strong>${a}</strong> – ${safe(b)}</li>`).join(''); }
function renderHabitGrid(){ const wrap = byId('habitGrid'); wrap.innerHTML = habits.map(h => `<div class="habit" id="habit_${h.id}" tabindex="0" role="button"><div><div style="font-weight:800">${safe(h.text)}</div><div class="tiny muted">Trykk for å veksle</div></div><div class="toggle"></div></div>`).join(''); habits.forEach(h => { const el = byId(`habit_${h.id}`); const action = () => toggleHabit(h.id); el.addEventListener('click', action); el.addEventListener('keydown', e => { if(e.key === 'Enter' || e.key === ' '){ e.preventDefault(); action(); } }); }); }
function updateHabitUi(id, active){ byId(`habit_${id}`)?.classList.toggle('active', !!active); }
function toggleHabit(id){ const current = state.checkins[today] || { habits:{}, waterGlasses:'', mood:'' }; current.habits = current.habits || {}; current.habits[id] = !current.habits[id]; state.checkins[today] = current; updateHabitUi(id, current.habits[id]); renderScore(); scheduleSave(); }
function renderMeals(){ const tbody = byId('mealTable'); if(!state.meals.length){ tbody.innerHTML = `<tr><td colspan="6" class="muted">Ingen måltider registrert enda.</td></tr>`; return; } tbody.innerHTML = [...state.meals].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(item => `<tr><td>${safe(item.date)}</td><td>${safe(item.type)}</td><td>${safe(item.text)}</td><td>${item.calories ? fmtInt(item.calories) : ''}</td><td>${item.protein ? fmtInt(item.protein) : ''}</td><td><button class="btn secondary" data-delmeal="${item.id}" style="padding:8px 10px">Slett</button></td></tr>`).join(''); tbody.querySelectorAll('[data-delmeal]').forEach(btn => btn.addEventListener('click', () => { state.meals = state.meals.filter(x => x.id !== btn.dataset.delmeal); renderAll(); scheduleSave(); })); }
function renderActivities(){ const tbody = byId('activityTable'); if(!state.activities.length){ tbody.innerHTML = `<tr><td colspan="6" class="muted">Ingen aktivitet registrert enda.</td></tr>`; return; } tbody.innerHTML = [...state.activities].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(item => `<tr><td>${safe(item.date)}</td><td>${safe(item.type)}</td><td>${item.duration ? fmtInt(item.duration) : ''}</td><td>${item.steps ? fmtInt(item.steps) : ''}</td><td>${item.calories ? fmtInt(item.calories) : ''}</td><td><button class="btn secondary" data-delact="${item.id}" style="padding:8px 10px">Slett</button></td></tr>`).join(''); tbody.querySelectorAll('[data-delact]').forEach(btn => btn.addEventListener('click', () => { state.activities = state.activities.filter(x => x.id !== btn.dataset.delact); renderAll(); scheduleSave(); })); }
function drawRoundRect(ctx,x,y,w,h,r){ ctx.beginPath(); ctx.moveTo(x+r,y); ctx.arcTo(x+w,y,x+w,y+h,r); ctx.arcTo(x+w,y+h,x,y+h,r); ctx.arcTo(x,y+h,x,y,r); ctx.arcTo(x,y,x+w,y,r); ctx.closePath(); }
function drawCardBg(ctx,w,h){ drawRoundRect(ctx,0,0,w,h,18); ctx.fillStyle = 'rgba(255,255,255,.03)'; ctx.fill(); ctx.strokeStyle = 'rgba(255,255,255,.12)'; ctx.stroke(); }
function drawWeightChart(){ const c = byId('weightChart'); const ctx = c.getContext('2d'); const w = c.width, h = c.height; ctx.clearRect(0,0,w,h); drawCardBg(ctx,w,h); const items = [...state.weights].sort((a,b)=>String(a.date).localeCompare(String(b.date))); if(!items.length){ ctx.fillStyle = '#9fb3d1'; ctx.fillText('Ingen veiinger ennå.', w/2 - 60, h/2); return; } const pad = {l:54,r:16,t:18,b:36}; const vals = items.map(x => Number(x.weight)); const min = Math.min(...vals, Number(state.profile.goalWeight || 0)) - 1; const max = Math.max(...vals, Number(state.profile.startWeight || 0)) + 1; ctx.strokeStyle = 'rgba(255,255,255,.12)'; ctx.fillStyle = '#9fb3d1'; ctx.font = '12px Segoe UI'; for(let i=0;i<5;i++){ const y = pad.t + i*((h-pad.t-pad.b)/4); ctx.beginPath(); ctx.moveTo(pad.l,y); ctx.lineTo(w-pad.r,y); ctx.stroke(); const value = max - i*((max-min)/4); ctx.fillText(Number(value).toLocaleString('no-NO',{maximumFractionDigits:1}), 10, y+4); } const mapX = i => items.length === 1 ? w/2 : pad.l + i*((w-pad.l-pad.r)/(items.length-1)); const mapY = v => pad.t + ((max-v)/(max-min || 1))*(h-pad.t-pad.b); const gy = mapY(Number(state.profile.goalWeight || 0)); ctx.setLineDash([6,5]); ctx.strokeStyle = '#22c55e'; ctx.beginPath(); ctx.moveTo(pad.l,gy); ctx.lineTo(w-pad.r,gy); ctx.stroke(); ctx.setLineDash([]); ctx.strokeStyle = '#60a5fa'; ctx.lineWidth = 3; ctx.beginPath(); items.forEach((it,i)=>{ const x=mapX(i), y=mapY(Number(it.weight)); if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y); }); ctx.stroke(); items.forEach((it,i)=>{ const x=mapX(i), y=mapY(Number(it.weight)); ctx.beginPath(); ctx.arc(x,y,4.5,0,Math.PI*2); ctx.fillStyle = '#5eead4'; ctx.fill(); if(i % Math.max(1, Math.ceil(items.length / 6)) === 0 || i === items.length-1){ ctx.fillStyle='#9fb3d1'; ctx.fillText(String(it.date).slice(5), x-12, h-14); } }); }
function drawActivityChart(){ const c = byId('activityChart'); const ctx = c.getContext('2d'); const w = c.width, h = c.height; ctx.clearRect(0,0,w,h); drawCardBg(ctx,w,h); const days=[]; for(let i=13;i>=0;i--){ const d=new Date(); d.setDate(d.getDate()-i); days.push(d.toISOString().slice(0,10)); } const bars = days.map(d => ({ date:d, minutes: state.activities.filter(a=>sameDay(a.date,d)).reduce((s,a)=>s+(parseFloat(a.duration)||0),0), calories: state.meals.filter(m=>sameDay(m.date,d)).reduce((s,m)=>s+(parseFloat(m.calories)||0),0)})); const maxVal = Math.max(60, ...bars.map(b => Math.max(b.minutes, (b.calories || 0) / 20))); const pad = {l:42,r:20,t:18,b:36}; ctx.strokeStyle='rgba(255,255,255,.12)'; for(let i=0;i<4;i++){ const y=pad.t + i*((h-pad.t-pad.b)/3); ctx.beginPath(); ctx.moveTo(pad.l,y); ctx.lineTo(w-pad.r,y); ctx.stroke(); } const spacing=(w-pad.l-pad.r)/bars.length; bars.forEach((b,i)=>{ const x=pad.l+i*spacing+4; const maxH=h-pad.t-pad.b; const h1=(b.minutes/maxVal)*maxH; const h2=(((b.calories || 0)/20)/maxVal)*maxH; ctx.fillStyle='#60a5fa'; ctx.fillRect(x,h-pad.b-h1,spacing/2-6,h1); ctx.fillStyle='#f59e0b'; ctx.fillRect(x+spacing/2-2,h-pad.b-h2,spacing/2-6,h2); if(i % 2 === 0){ ctx.fillStyle='#9fb3d1'; ctx.font='11px Segoe UI'; ctx.fillText(b.date.slice(5), x-2, h-12); } }); ctx.fillStyle='#60a5fa'; ctx.fillRect(pad.l,10,14,10); ctx.fillStyle='#dbeafe'; ctx.fillText('Aktive minutter', pad.l+22,19); ctx.fillStyle='#f59e0b'; ctx.fillRect(pad.l+125,10,14,10); ctx.fillStyle='#fde68a'; ctx.fillText('Kalorier / 20', pad.l+147,19); }
function renderCharts(){ drawWeightChart(); drawActivityChart(); }
function renderAll(){ syncUi(); renderSummary(); renderGoals(); renderScore(); renderMeals(); renderActivities(); renderCharts(); updateFirebaseStatus(); }
function saveProfile(){ const p = state.profile; p.displayName = val('displayName'); p.heightCm = num('heightCm', p.heightCm); p.age = val('age'); p.sex = val('sex'); p.activityLevel = val('activityLevel') || '1.55'; p.manualCalorieTarget = val('manualCalorieTarget'); p.startWeight = num('startWeight', p.startWeight); p.currentWeight = num('currentWeight', p.currentWeight); p.goalWeight = num('goalWeight', p.goalWeight); p.why = val('whyText'); renderAll(); scheduleSave(); if(firebaseReady && currentUser && p.displayName && currentUser.displayName !== p.displayName){ updateProfile(currentUser, { displayName: p.displayName }).catch(() => {}); setText('userLabel', p.displayName); } }
function logWeight(){ saveProfile(); const entry = { id: cryptoRandom(), date: val('weighDate') || today, weight: num('currentWeight', state.profile.currentWeight) }; state.profile.currentWeight = entry.weight; state.weights.push(entry); const map = new Map(); state.weights.forEach(item => map.set(item.date, item)); state.weights = [...map.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))); renderAll(); scheduleSave(); setNotice('Veiing lagret.', 'success'); }
function addMeal(prefill){ const item = prefill || { id: cryptoRandom(), date: val('mealDate') || today, type: val('mealType'), text: val('mealText'), calories: val('mealCalories'), protein: val('mealProtein'), note: val('mealNote') }; if(!item.text){ alert('Skriv inn hva du spiste.'); return; } state.meals.unshift(item); ['mealText','mealCalories','mealProtein','mealNote'].forEach(id => byId(id).value = ''); renderAll(); scheduleSave(); }
function addActivity(prefill){ const item = prefill || { id: cryptoRandom(), date: val('activityDate') || today, type: val('activityType'), duration: val('activityDuration'), steps: val('activitySteps'), calories: val('activityCalories'), note: val('activityNote') }; if(!item.duration && !item.steps && !item.calories){ alert('Legg inn minutter, skritt eller kalorier.'); return; } state.activities.unshift(item); ['activityDuration','activitySteps','activityCalories','activityNote'].forEach(id => byId(id).value = ''); renderAll(); scheduleSave(); }
function saveGoals(){ state.goals.activitiesPerWeek = num('goalActivitiesPerWeek', state.goals.activitiesPerWeek); state.goals.minutesPerWeek = num('goalMinutesPerWeek', state.goals.minutesPerWeek); state.goals.stepsPerDay = num('goalStepsPerDay', state.goals.stepsPerDay); renderAll(); scheduleSave(); }
function saveCheckin(){ const current = state.checkins[today] || { habits:{} }; current.waterGlasses = num('waterGlasses', 0); current.mood = val('dailyMood'); state.checkins[today] = current; renderAll(); scheduleSave(); }
function exportJson(){ const blob = new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download='vektreise-cloud-backup.json'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(a.href), 500); }
function importJson(file){ if(!file) return; const reader = new FileReader(); reader.onload = () => { try{ state = mergeDeep(defaultState(), JSON.parse(reader.result)); renderAll(); scheduleSave(); setNotice('JSON importert.', 'success'); } catch { alert('Kunne ikke lese JSON-filen.'); } }; reader.readAsText(file); }
function detectDelimiter(text){ const first = text.split(/?
/).find(Boolean) || ''; return [',',';','	'].sort((a,b)=>first.split(b).length-first.split(a).length)[0] || ','; }
function splitCsvLine(line, delimiter){ const out=[]; let cur='', quoted=false; for(let i=0;i<line.length;i++){ const ch=line[i]; if(ch === '"'){ if(quoted && line[i+1] === '"'){ cur += '"'; i++; } else quoted = !quoted; } else if(ch === delimiter && !quoted){ out.push(cur); cur=''; } else cur += ch; } out.push(cur); return out; }
function parseCsv(text){ const delimiter = detectDelimiter(text); const lines = text.split(/?
/).filter(Boolean); if(lines.length < 2) return []; const headers = splitCsvLine(lines[0], delimiter).map(h => h.trim()); return lines.slice(1).map(line => { const cols = splitCsvLine(line, delimiter); const obj={}; headers.forEach((h,i)=>obj[h]=(cols[i] || '').trim()); return obj; }); }
function findField(row, names){ const keys=Object.keys(row); const lower=keys.map(k=>k.toLowerCase()); for(const name of names){ const idx=lower.findIndex(k=>k === name || k.includes(name)); if(idx >= 0) return row[keys[idx]]; } return ''; }
function normalizeDate(value){ if(!value) return ''; const raw = String(value).trim(); const direct = new Date(raw); if(!isNaN(direct)) return direct.toISOString().slice(0,10); const m = raw.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})$/); if(m){ const dd=m[1].padStart(2,'0'); const mm=m[2].padStart(2,'0'); let yyyy=m[3]; if(yyyy.length === 2) yyyy = `20${yyyy}`; return `${yyyy}-${mm}-${dd}`; } return ''; }
function parseDurationToMinutes(v){ if(v == null || v === '') return 0; const s=String(v).trim(); if(/^\d+(\.\d+)?$/.test(s)) return Math.round(parseFloat(s)); const parts=s.split(':').map(n=>n.trim()); if(parts.length === 3) return Math.round(Number(parts[0])*60 + Number(parts[1]) + Number(parts[2])/60); if(parts.length === 2) return Math.round(Number(parts[0])*60 + Number(parts[1])); const h=/(\d+(?:\.\d+)?)\s*h/.exec(s); const m=/(\d+(?:\.\d+)?)\s*m/.exec(s); const sec=/(\d+(?:\.\d+)?)\s*s/.exec(s); return Math.round((h ? Number(h[1])*60 : 0) + (m ? Number(m[1]) : 0) + (sec ? Number(sec[1])/60 : 0)); }
function importGarmin(file){ if(!file) return; const reader = new FileReader(); reader.onload = () => { try{ const rows = parseCsv(reader.result); let imported = 0; rows.forEach(row => { const date = normalizeDate(findField(row, ['date','dato','activity date','start time'])); const type = findField(row, ['activity type','type','aktivitet']) || 'Garmin-aktivitet'; const duration = parseDurationToMinutes(findField(row, ['duration','session time','elapsed time','varighet'])); const steps = parseFloat(String(findField(row, ['steps','skritt'])).replace(/[^0-9.,-]/g,'').replace(',','.')) || 0; const calories = parseFloat(String(findField(row, ['calories','kcal','energi'])).replace(/[^0-9.,-]/g,'').replace(',','.')) || 0; const distance = findField(row, ['distance','distanse']); if(!date && !duration && !steps && !calories) return; state.activities.unshift({ id: cryptoRandom(), date: date || today, type, duration: duration || '', steps: steps || '', calories: calories || '', note: distance ? `Importert fra Garmin • distanse ${distance}` : 'Importert fra Garmin' }); imported++; }); renderAll(); scheduleSave(); setNotice(`Garmin-import fullført: ${imported} rader.`, 'success'); } catch(err){ alert(`Kunne ikke lese CSV: ${err.message}`); } }; reader.readAsText(file, 'utf-8'); }
function downloadTemplateCsv(){ const csv='Date,Activity Type,Duration,Steps,Calories,Distance
2026-06-15,Gåtur,45,8200,340,5.8
2026-06-14,Golf,180,13000,900,9.4'; const blob = new Blob([csv], { type:'text/csv;charset=utf-8' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download='garmin-import-mal.csv'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(a.href), 500); }
async function doAuth(){ if(!firebaseReady){ byId('authOverlay').classList.add('hidden'); setNotice('Demo-modus aktiv. Fyll ut firebase-config.js og aktiver Email/Password i Firebase.', 'warn'); return; } const email = val('authEmail'); const password = val('authPassword'); const name = val('authName'); try{ showAuthMessage('Jobber…'); if(authMode === 'login') await signInWithEmailAndPassword(auth, email, password); else if(authMode === 'signup'){ const cred = await createUserWithEmailAndPassword(auth, email, password); if(name) await updateProfile(cred.user, { displayName: name }); } else { await sendPasswordResetEmail(auth, email); showAuthMessage('E-post for nullstilling sendt.'); return; } showAuthMessage('OK'); } catch(err){ showAuthMessage(err.message); } }
function bind(){ renderHabitGrid(); renderAll(); setText('quoteText', quotes[Math.floor(Math.random()*quotes.length)]); ['weighDate','mealDate','activityDate'].forEach(id => byId(id).value = today); document.querySelectorAll('[data-tab]').forEach(el => el.addEventListener('click', () => setAuthMode(el.dataset.tab))); byId('authActionBtn').addEventListener('click', doAuth); byId('saveProfileBtn').addEventListener('click', saveProfile); byId('logWeightBtn').addEventListener('click', logWeight); byId('addMealBtn').addEventListener('click', () => addMeal()); byId('addActivityBtn').addEventListener('click', () => addActivity()); byId('saveGoalsBtn').addEventListener('click', saveGoals); byId('saveCheckinBtn').addEventListener('click', saveCheckin); byId('quoteBtn').addEventListener('click', () => setText('quoteText', quotes[Math.floor(Math.random()*quotes.length)])); byId('exportBtn').addEventListener('click', exportJson); byId('importJsonBtn').addEventListener('click', () => byId('importJsonFile').click()); byId('importJsonFile').addEventListener('change', e => importJson(e.target.files?.[0])); byId('garminBtn').addEventListener('click', () => byId('garminFile').click()); byId('garminFile').addEventListener('change', e => importGarmin(e.target.files?.[0])); byId('templateCsvBtn').addEventListener('click', downloadTemplateCsv); byId('logoutBtn').addEventListener('click', async () => { if(firebaseReady && auth) await signOut(auth); else byId('authOverlay').classList.remove('hidden'); }); byId('syncBtn').addEventListener('click', () => { if(firebaseReady && currentUser) pushToCloud(false); else setNotice('Ingen innlogget Firebase-bruker akkurat nå.', 'warn'); }); window.addEventListener('resize', () => renderCharts()); }
bind(); initFirebase();
